### ISSUE TITLE
Copyright sign © is not correctly added to file

### ISSUE THREAD

**Issue by rlazdauskas** [rpau/walkmod-license-applier-plugin#1]
I have license-header.txt file with content:
"Some copyright © of some group"

I execute license applier plugin (using maven plugin). It adds license to files, but it changes a bit:

"Some copyright Â© of some group"

It somehow adds strange sign Â near ©. As this "copyright" sign should be quite common in license header, maybe there is possibility to investigate how to fix it?

**Comment by rpau** [comment]
This is an encoding issue. Is your file written in UTF-8?

**Comment by rlazdauskas** [comment]
My license-header.txt is simple txt file.
I tried to write sign like this: 
© (ALT + 0169)
&#169;
&copy;
\u00A9

**Comment by rlazdauskas** [comment]
second is .&#169; (without dot)
third was .&copy; (without dot)

**Comment by rlazdauskas** [comment]
copy; (with & sign in begining)
#169; (with & sign in begining)

**Comment by rpau** [comment]
Sorry, but I do not get what you mean. The important thing is to save the text file in UTF-8 format from your editor. Afterwards, you need to write © like you would write it in any editor.

**Comment by rlazdauskas** [comment]
Saved file in UTF-8 format - still same problem persists. Also now in begining of the license new symbols are added "ï»¿"

So now after run it is shown like this:
/\*  ï»¿Some copyright Â© of some group*/

[license-header.txt](https://github.com/walkmod/walkmod-license-applier-plugin/files/338887/license-header.txt)

**Comment by rpau** [comment]
Ok, perfect.

Let me try

**Comment by rpau** [comment]
Hi,

I cannot reproduce the error. I suspect that your java files are not in UTF-8. What is the encoding you use? Are you in windows?

**Comment by rlazdauskas** [comment]
I can confirm that my companies java files (all of them) are saved in UTF-8. And yes I am using Windows 7 Proffesional

**Comment by rlazdauskas** [comment]
You were correct, it was encoding issue, but saving license-header.txt file to UTF-8 didin't solve the problem (added more). But tried other formats, and in the end saving license-header.txt to 'ANSI' format helped - plugin added everything how it supposed to be. 
For now closing this issue.
